sudo: required
services:
  - docker

before_install:
  - docker build -t scubawill/docker-react -f Dockerfile.dev .

script: # Run our test suite
  - docker run -e CI=true scubawill/docker-react  npm run test -- --coverage

deploy: # Deploy our application to AWS
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-303344215438"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"